﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers.FastTree;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace Recomendation
{
    public partial class Recomendation
    {
        /// <summary>
        /// Retrains model using the pipeline generated as part of the training process. For more information on how to load data, see aka.ms/loaddata.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <param name="trainData"></param>
        /// <returns></returns>
        public static ITransformer RetrainPipeline(MLContext mlContext, IDataView trainData)
        {
            var pipeline = BuildPipeline(mlContext);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"IDContent", @"IDContent"),new InputOutputColumnPair(@"CategoryID", @"CategoryID"),new InputOutputColumnPair(@"Tophot", @"Tophot"),new InputOutputColumnPair(@"GiaTien", @"GiaTien")})      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"Name",outputColumnName:@"Name"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"TacGia",outputColumnName:@"TacGia"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"NhaXuatBan",outputColumnName:@"NhaXuatBan"))      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"IDContent",@"CategoryID",@"Tophot",@"GiaTien",@"Name",@"TacGia",@"NhaXuatBan"}))      
                                    .Append(mlContext.Regression.Trainers.FastForest(new FastForestRegressionTrainer.Options(){NumberOfTrees=4,NumberOfLeaves=4,FeatureFraction=1F,LabelColumnName=@"LuotXem",FeatureColumnName=@"Features"}));

            return pipeline;
        }
    }
}
